### ISSUE TITLE
Train-test split

### ISSUE THREAD

**Issue by udaykusupati** [hjwdzh/FrameNet#1]
I see the train-test split is not the one provided in the scannet dataset(neither v1 nor v2). Can you please elaborate on how this split was chosen?

**Comment by hjwdzh** [comment]
Thanks for the interest. The split is actually done by os.listdir() to the scannet folders, and split by 1:3 (maybe 1:4, I don't remember the details). Since the train/test are fully separated by different scenes, it should be fine. If you want to split using scannet v2 style, you might need to do some coding on your own.

**Comment by udaykusupati** [comment]
Thanks for the reply!
I see you implement the other architectures yourself too and the results on scannet reported in the paper follow this split. I wanted to compare our current work with these numbers but I was using the scannet v2 split. But the two splits are entirely different. So I will probably need to use your split for training and testing to compare against other architectures mentioned in your paper. Please let me know if I am wrong.

**Comment by hjwdzh** [comment]
I think that's pretty fair:) I will close the issue for now, and please feel free to open it if you still have questions.
